from crewai import Agent, Task, LLM
from agents.tasks.reflection  import refine_answer_task
from rag_pipeline.utils.logger import log_data

 
# Define the Reflection Agent
llm = LLM(model="gemini/gemini-2.0-flash")
reflection_agent = Agent(
    role="Refine and self-correct draft answers",
    goal="Refine and structure the answer generated by the reasoning agent (Reasoning's generate answer task) to ensure it is accurate, concise, "
    "and clear, using a custom LLM-based refinement method.",
    backstory="You specialize in reviewing and refining AI-generated answers. Using a custom LLM-based method, your role is to ensure that the answers are accurate, concise, and clear."
    " You focus on improving structure, clarity, and correctness, ensuring that the final answer meets the highest standards before being delivered.",
    tasks=[refine_answer_task],
    llm="gemini/gemini-2.0-flash",
    function_calling_llm=llm,   
    max_rpm=10,
    verbose=True,
    max_retry_limit=2,  
    max_iter=5   

)

refine_answer_task.agent = reflection_agent

 




